{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "name": "study.ipynb",
      "authorship_tag": "ABX9TyN4q9Gktvo4UAkJ6mwwZUND",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "version_major": 2,
        "version_minor": 0,
        "state": {
          "03cc9cc176f24bd0aa6f56c1c29d99ca": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "VBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "VBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "VBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_7ca42cbd3922446383d6908d8c7875d9",
                "IPY_MODEL_828fc1d5a3964830970b9afeea4b369b",
                "IPY_MODEL_6ac5dd0dfb714731b631a30a21460282",
                "IPY_MODEL_9da7e91e36374b438c6d78e840d162fa",
                "IPY_MODEL_7eb561269b8c4c2185cd92d3717c3b47",
                "IPY_MODEL_ab920671a62d40b1b5fd2ee28d332fb9"
              ],
              "layout": "IPY_MODEL_a9c335fa5af54799a0608d0b163ea75e"
            }
          },
          "7ca42cbd3922446383d6908d8c7875d9": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "P (atm):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_bb95831474044493b2b4a45d0f0f8ff6",
              "step": null,
              "style": "IPY_MODEL_f529d0cefb154a8587dfa0443bb40b7e",
              "value": 1
            }
          },
          "828fc1d5a3964830970b9afeea4b369b": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "V (L):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_5c5ac32f8e6649859e4abec568d8c5fc",
              "step": null,
              "style": "IPY_MODEL_f15b83d732294a44953e942a74cdce9d",
              "value": 22.4
            }
          },
          "6ac5dd0dfb714731b631a30a21460282": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "T (K):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_c848d149b9da4fb2b7835afae5625a92",
              "step": null,
              "style": "IPY_MODEL_22054f6474274179ab3b31ed8a263585",
              "value": 273.15
            }
          },
          "9da7e91e36374b438c6d78e840d162fa": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "Mass (g):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_37e507a7887f432094833c72e06bc54c",
              "step": null,
              "style": "IPY_MODEL_ca3a9a54371241768356be507ba7b328",
              "value": 28.01
            }
          },
          "7eb561269b8c4c2185cd92d3717c3b47": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatSliderModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatSliderModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatSliderView",
              "continuous_update": true,
              "description": "Error (%):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_56bbb8e7668b4670bad019cafb940642",
              "max": 0.5,
              "min": 0,
              "orientation": "horizontal",
              "readout": true,
              "readout_format": ".2f",
              "step": 0.01,
              "style": "IPY_MODEL_1e023b706b024e59ac7ddd94294114a0",
              "value": 0.1
            }
          },
          "ab920671a62d40b1b5fd2ee28d332fb9": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ButtonModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ButtonModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ButtonView",
              "button_style": "primary",
              "description": "계산하기",
              "disabled": false,
              "icon": "",
              "layout": "IPY_MODEL_38d71ac0ce6e43ea87ee90c944fbf7f8",
              "style": "IPY_MODEL_b95fd87325a14efe96ba7e9745d78efa",
              "tooltip": ""
            }
          },
          "a9c335fa5af54799a0608d0b163ea75e": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "bb95831474044493b2b4a45d0f0f8ff6": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "f529d0cefb154a8587dfa0443bb40b7e": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "5c5ac32f8e6649859e4abec568d8c5fc": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "f15b83d732294a44953e942a74cdce9d": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "c848d149b9da4fb2b7835afae5625a92": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "22054f6474274179ab3b31ed8a263585": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "37e507a7887f432094833c72e06bc54c": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "ca3a9a54371241768356be507ba7b328": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "56bbb8e7668b4670bad019cafb940642": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "1e023b706b024e59ac7ddd94294114a0": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "SliderStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "SliderStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": "",
              "handle_color": null
            }
          },
          "38d71ac0ce6e43ea87ee90c944fbf7f8": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "b95fd87325a14efe96ba7e9745d78efa": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ButtonStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ButtonStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "button_color": null,
              "font_weight": ""
            }
          },
          "1b23fa19477c48e29f2da3b0f2eb97f9": {
            "model_module": "@jupyter-widgets/output",
            "model_name": "OutputModel",
            "model_module_version": "1.0.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/output",
              "_model_module_version": "1.0.0",
              "_model_name": "OutputModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/output",
              "_view_module_version": "1.0.0",
              "_view_name": "OutputView",
              "layout": "IPY_MODEL_245dcccf26ac42e6a93ffb57967d8622",
              "msg_id": "",
              "outputs": [
                {
                  "output_type": "stream",
                  "name": "stdout",
                  "text": [
                    "[결과] 계산된 분자량: 28.01 g/mol\n",
                    "Multiple possible matches found: Nitrogen (N2), Carbon Monoxide (CO), Ethane (C2H6), Nitric Oxide (NO), Ethylene (C2H4), Acetylene (C2H2) (Calculated M: 28.01 g/mol)\n"
                  ]
                }
              ]
            }
          },
          "245dcccf26ac42e6a93ffb57967d8622": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/tototo24-create/gdp-dashboard/blob/main/study.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8de9f86b"
      },
      "source": [
        "# Gas Identification Device using Ideal Gas Law\n",
        "\n",
        "This notebook implements a simple device to identify an unknown ideal gas by measuring its pressure (P), volume (V), temperature (T), and mass. The identification is based on the calculated molecular weight (M) using the ideal gas law and comparing it against a list of known gases within a specified error range."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "269dd9c2"
      },
      "source": [
        "# Define the Ideal Gas Constant (R) and the allowed error percentage\n",
        "R = 0.082  # L·atm/(mol·K)\n",
        "ERROR_PERCENTAGE = 0.20 # 20% error margin"
      ],
      "execution_count": 1,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "f2f2e876"
      },
      "source": [
        "## 40 Representative Gases and their Molecular Weights\n",
        "\n",
        "Below is a list of 40 common gases with their approximate molecular weights (g/mol). This list will be used to identify the unknown gas. Please note that these are rounded values and may vary slightly depending on the source."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "2a908e8a"
      },
      "source": [
        "# Dictionary of known gases and their molecular weights (g/mol)\n",
        "known_gases = {\n",
        "    'Hydrogen (H2)': 2.016,\n",
        "    'Helium (He)': 4.003,\n",
        "    'Methane (CH4)': 16.04,\n",
        "    'Ammonia (NH3)': 17.03,\n",
        "    'Water Vapor (H2O)': 18.015,\n",
        "    'Neon (Ne)': 20.18,\n",
        "    'Nitrogen (N2)': 28.01,\n",
        "    'Carbon Monoxide (CO)': 28.01,\n",
        "    'Ethane (C2H6)': 30.07,\n",
        "    'Oxygen (O2)': 32.00,\n",
        "    'Hydrogen Sulfide (H2S)': 34.08,\n",
        "    'Argon (Ar)': 39.95,\n",
        "    'Carbon Dioxide (CO2)': 44.01,\n",
        "    'Nitrous Oxide (N2O)': 44.01,\n",
        "    'Propane (C3H8)': 44.10,\n",
        "    'Butane (C4H10)': 58.12,\n",
        "    'Sulfur Dioxide (SO2)': 64.07,\n",
        "    'Chlorine (Cl2)': 70.91,\n",
        "    'Krypton (Kr)': 83.80,\n",
        "    'Xenon (Xe)': 131.29,\n",
        "    'Sulfur Hexafluoride (SF6)': 146.06,\n",
        "    'Fluorine (F2)': 37.99,\n",
        "    'Ozone (O3)': 47.997,\n",
        "    'Nitric Oxide (NO)': 30.01,\n",
        "    'Nitrogen Dioxide (NO2)': 46.01,\n",
        "    'Hydrogen Chloride (HCl)': 36.46,\n",
        "    'Hydrogen Fluoride (HF)': 20.01,\n",
        "    'Ethylene (C2H4)': 28.05,\n",
        "    'Acetylene (C2H2)': 26.04,\n",
        "    'Propylene (C3H6)': 42.08,\n",
        "    'Butylene (C4H8)': 56.11,\n",
        "    'Pentane (C5H12)': 72.15,\n",
        "    'Hexane (C6H14)': 86.18,\n",
        "    'Heptane (C7H16)': 100.21,\n",
        "    'Octane (C8H18)': 114.23,\n",
        "    'Benzene (C6H6)': 78.11,\n",
        "    'Toluene (C7H8)': 92.14,\n",
        "    'Methanol (CH3OH)': 32.04,\n",
        "    'Ethanol (C2H5OH)': 46.07,\n",
        "    'Diethyl Ether ((C2H5)2O)': 74.12\n",
        "}"
      ],
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "61b6adf9"
      },
      "source": [
        "## Functions for Gas Identification\n",
        "\n",
        "Here we define two functions:\n",
        "1.  `calculate_molecular_weight`: Computes the molecular weight using the ideal gas law (PV = (mass/M)RT).\n",
        "2.  `identify_gas`: Takes the calculated molecular weight and searches for a match within the `known_gases` list, considering the `ERROR_PERCENTAGE`."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "5d52df01"
      },
      "source": [
        "def calculate_molecular_weight(P, V, T, mass, R=R):\n",
        "    \"\"\"\n",
        "    Calculates the molecular weight of a gas using the ideal gas law.\n",
        "\n",
        "    Args:\n",
        "        P (float): Pressure in atmospheres (atm).\n",
        "        V (float): Volume in liters (L).\n",
        "        T (float): Temperature in Kelvin (K).\n",
        "        mass (float): Mass of the gas in grams (g).\n",
        "        R (float): Ideal gas constant (L·atm/(mol·K)). Default is 0.082.\n",
        "\n",
        "    Returns:\n",
        "        float: Calculated molecular weight in g/mol.\n",
        "    \"\"\"\n",
        "    # Ensure T is not zero to avoid division by zero\n",
        "    if T == 0:\n",
        "        raise ValueError(\"Temperature cannot be zero Kelvin.\")\n",
        "    # Ensure P and V are not zero or negative for meaningful calculation\n",
        "    if P <= 0 or V <= 0:\n",
        "        raise ValueError(\"Pressure and Volume must be positive.\")\n",
        "    # Ensure mass is positive\n",
        "    if mass <= 0:\n",
        "        raise ValueError(\"Mass must be positive.\")\n",
        "\n",
        "    # Ideal gas law: PV = nRT, where n = mass / M (Molecular Weight)\n",
        "    # So, PV = (mass / M)RT\n",
        "    # Rearranging for M: M = (mass * R * T) / (P * V)\n",
        "    molecular_weight = (mass * R * T) / (P * V)\n",
        "    return molecular_weight\n",
        "\n",
        "def identify_gas(calculated_M, known_gases, error_percentage):\n",
        "    \"\"\"\n",
        "    Identifies a gas by comparing its calculated molecular weight to a list of known gases\n",
        "    within a specified error percentage.\n",
        "\n",
        "    Args:\n",
        "        calculated_M (float): The molecular weight calculated from experimental data.\n",
        "        known_gases (dict): A dictionary where keys are gas names (str) and values are\n",
        "                            their known molecular weights (float).\n",
        "        error_percentage (float): The allowed percentage error for identification (e.g., 0.20 for 20%).\n",
        "\n",
        "    Returns:\n",
        "        str: The identified gas name, or a message indicating no match found.\n",
        "    \"\"\"\n",
        "    possible_matches = []\n",
        "    for gas_name, known_M in known_gases.items():\n",
        "        lower_bound = known_M * (1 - error_percentage)\n",
        "        upper_bound = known_M * (1 + error_percentage)\n",
        "\n",
        "        if lower_bound <= calculated_M <= upper_bound:\n",
        "            possible_matches.append(gas_name)\n",
        "\n",
        "    if not possible_matches:\n",
        "        return \"No matching gas found within the specified error range.\"\n",
        "    elif len(possible_matches) == 1:\n",
        "        return f\"Identified Gas: {possible_matches[0]} (Calculated M: {calculated_M:.2f} g/mol)\"\n",
        "    else:\n",
        "        return f\"Multiple possible matches found: {', '.join(possible_matches)} (Calculated M: {calculated_M:.2f} g/mol)\""
      ],
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "61df4fc6"
      },
      "source": [
        "## Demonstration\n",
        "\n",
        "Let's test the device with some example values."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "62634d04",
        "outputId": "474b412d-5b96-47ee-c3fb-c645837f25d2"
      },
      "source": [
        "# Example 1: Known gas (e.g., Nitrogen N2)\n",
        "P_ex1 = 1.0     # atm\n",
        "V_ex1 = 22.4    # L (approx. molar volume at STP)\n",
        "T_ex1 = 273.15  # K (0 degrees Celsius)\n",
        "mass_ex1 = 28.01 # g (approx. mass of 1 mole of N2)\n",
        "\n",
        "calculated_M_ex1 = calculate_molecular_weight(P_ex1, V_ex1, T_ex1, mass_ex1)\n",
        "print(f\"Example 1 - Calculated Molecular Weight: {calculated_M_ex1:.2f} g/mol\")\n",
        "identification_ex1 = identify_gas(calculated_M_ex1, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 1 - {identification_ex1}\\n\")\n",
        "\n",
        "# Example 2: Another known gas (e.g., Carbon Dioxide CO2)\n",
        "P_ex2 = 1.2     # atm\n",
        "V_ex2 = 20.0    # L\n",
        "T_ex2 = 300.0   # K\n",
        "mass_ex2 = 48.0 # g (slightly more than 1 mole of CO2)\n",
        "\n",
        "calculated_M_ex2 = calculate_molecular_weight(P_ex2, V_ex2, T_ex2, mass_ex2)\n",
        "print(f\"Example 2 - Calculated Molecular Weight: {calculated_M_ex2:.2f} g/mol\")\n",
        "identification_ex2 = identify_gas(calculated_M_ex2, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 2 - {identification_ex2}\\n\")\n",
        "\n",
        "# Example 3: Values that might not match perfectly or result in multiple matches\n",
        "P_ex3 = 0.95    # atm\n",
        "V_ex3 = 25.0    # L\n",
        "T_ex3 = 280.0   # K\n",
        "mass_ex3 = 20.0 # g (hypothetical)\n",
        "\n",
        "calculated_M_ex3 = calculate_molecular_weight(P_ex3, V_ex3, T_ex3, mass_ex3)\n",
        "print(f\"Example 3 - Calculated Molecular Weight: {calculated_M_ex3:.2f} g/mol\")\n",
        "identification_ex3 = identify_gas(calculated_M_ex3, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 3 - {identification_ex3}\")"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Example 1 - Calculated Molecular Weight: 28.01 g/mol\n",
            "Example 1 - Multiple possible matches found: Nitrogen (N2), Carbon Monoxide (CO), Ethane (C2H6), Oxygen (O2), Hydrogen Sulfide (H2S), Nitric Oxide (NO), Ethylene (C2H4), Acetylene (C2H2), Methanol (CH3OH) (Calculated M: 28.01 g/mol)\n",
            "\n",
            "Example 2 - Calculated Molecular Weight: 49.20 g/mol\n",
            "Example 2 - Multiple possible matches found: Carbon Dioxide (CO2), Nitrous Oxide (N2O), Propane (C3H8), Butane (C4H10), Ozone (O3), Nitrogen Dioxide (NO2), Propylene (C3H6), Butylene (C4H8), Ethanol (C2H5OH) (Calculated M: 49.20 g/mol)\n",
            "\n",
            "Example 3 - Calculated Molecular Weight: 19.33 g/mol\n",
            "Example 3 - Multiple possible matches found: Ammonia (NH3), Water Vapor (H2O), Neon (Ne), Hydrogen Fluoride (HF) (Calculated M: 19.33 g/mol)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "3cd48b88"
      },
      "source": [
        "## Interactive Gas Identification\n",
        "\n",
        "Use the input fields below to adjust the parameters and identify an unknown gas."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "cee2cd57"
      },
      "source": [
        "## Custom Interactive Interface\n",
        "\n",
        "Below is a custom UI with a dedicated **Calculate** button."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 267,
          "referenced_widgets": [
            "03cc9cc176f24bd0aa6f56c1c29d99ca",
            "7ca42cbd3922446383d6908d8c7875d9",
            "828fc1d5a3964830970b9afeea4b369b",
            "6ac5dd0dfb714731b631a30a21460282",
            "9da7e91e36374b438c6d78e840d162fa",
            "7eb561269b8c4c2185cd92d3717c3b47",
            "ab920671a62d40b1b5fd2ee28d332fb9",
            "a9c335fa5af54799a0608d0b163ea75e",
            "bb95831474044493b2b4a45d0f0f8ff6",
            "f529d0cefb154a8587dfa0443bb40b7e",
            "5c5ac32f8e6649859e4abec568d8c5fc",
            "f15b83d732294a44953e942a74cdce9d",
            "c848d149b9da4fb2b7835afae5625a92",
            "22054f6474274179ab3b31ed8a263585",
            "37e507a7887f432094833c72e06bc54c",
            "ca3a9a54371241768356be507ba7b328",
            "56bbb8e7668b4670bad019cafb940642",
            "1e023b706b024e59ac7ddd94294114a0",
            "38d71ac0ce6e43ea87ee90c944fbf7f8",
            "b95fd87325a14efe96ba7e9745d78efa",
            "1b23fa19477c48e29f2da3b0f2eb97f9",
            "245dcccf26ac42e6a93ffb57967d8622"
          ]
        },
        "id": "63579ac3",
        "outputId": "73e26c70-6f67-4924-ebcf-3610d8dedae2"
      },
      "source": [
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "\n",
        "# Create input widgets\n",
        "p_input = widgets.FloatText(value=1.0, description='P (atm):')\n",
        "v_input = widgets.FloatText(value=22.4, description='V (L):')\n",
        "t_input = widgets.FloatText(value=273.15, description='T (K):')\n",
        "mass_input = widgets.FloatText(value=28.01, description='Mass (g):')\n",
        "error_slider = widgets.FloatSlider(value=0.1, min=0, max=0.5, step=0.01, description='Error (%):')\n",
        "calc_button = widgets.Button(description=\"계산하기\", button_style='primary')\n",
        "output_area = widgets.Output()\n",
        "\n",
        "def on_button_clicked(b):\n",
        "    with output_area:\n",
        "        clear_output()\n",
        "        try:\n",
        "            calc_M = calculate_molecular_weight(p_input.value, v_input.value, t_input.value, mass_input.value)\n",
        "            res = identify_gas(calc_M, known_gases, error_slider.value)\n",
        "            print(f\"[결과] 계산된 분자량: {calc_M:.2f} g/mol\")\n",
        "            print(res)\n",
        "        except Exception as e:\n",
        "            print(f\"오류 발생: {e}\")\n",
        "\n",
        "calc_button.on_click(on_button_clicked)\n",
        "\n",
        "# Layout\n",
        "ui = widgets.VBox([p_input, v_input, t_input, mass_input, error_slider, calc_button])\n",
        "display(ui, output_area)"
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "VBox(children=(FloatText(value=1.0, description='P (atm):'), FloatText(value=22.4, description='V (L):'), Floa…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "03cc9cc176f24bd0aa6f56c1c29d99ca"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Output()"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "1b23fa19477c48e29f2da3b0f2eb97f9"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}