# -*- coding: utf-8 -*-
"""교사 연수 수업용

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxM3oSIw0i1qnGU1CTkioxgVczXMn8KT

# Gas Identification Device using Ideal Gas Law

This notebook implements a simple device to identify an unknown ideal gas by measuring its pressure (P), volume (V), temperature (T), and mass. The identification is based on the calculated molecular weight (M) using the ideal gas law and comparing it against a list of known gases within a specified error range.
"""

# Define the Ideal Gas Constant (R) and the allowed error percentage
R = 0.082  # L·atm/(mol·K)
ERROR_PERCENTAGE = 0.20 # 20% error margin

"""## 40 Representative Gases and their Molecular Weights

Below is a list of 40 common gases with their approximate molecular weights (g/mol). This list will be used to identify the unknown gas. Please note that these are rounded values and may vary slightly depending on the source.
"""

# Dictionary of known gases and their molecular weights (g/mol)
known_gases = {
    'Hydrogen (H2)': 2.016,
    'Helium (He)': 4.003,
    'Methane (CH4)': 16.04,
    'Ammonia (NH3)': 17.03,
    'Water Vapor (H2O)': 18.015,
    'Neon (Ne)': 20.18,
    'Nitrogen (N2)': 28.01,
    'Carbon Monoxide (CO)': 28.01,
    'Ethane (C2H6)': 30.07,
    'Oxygen (O2)': 32.00,
    'Hydrogen Sulfide (H2S)': 34.08,
    'Argon (Ar)': 39.95,
    'Carbon Dioxide (CO2)': 44.01,
    'Nitrous Oxide (N2O)': 44.01,
    'Propane (C3H8)': 44.10,
    'Butane (C4H10)': 58.12,
    'Sulfur Dioxide (SO2)': 64.07,
    'Chlorine (Cl2)': 70.91,
    'Krypton (Kr)': 83.80,
    'Xenon (Xe)': 131.29,
    'Sulfur Hexafluoride (SF6)': 146.06,
    'Fluorine (F2)': 37.99,
    'Ozone (O3)': 47.997,
    'Nitric Oxide (NO)': 30.01,
    'Nitrogen Dioxide (NO2)': 46.01,
    'Hydrogen Chloride (HCl)': 36.46,
    'Hydrogen Fluoride (HF)': 20.01,
    'Ethylene (C2H4)': 28.05,
    'Acetylene (C2H2)': 26.04,
    'Propylene (C3H6)': 42.08,
    'Butylene (C4H8)': 56.11,
    'Pentane (C5H12)': 72.15,
    'Hexane (C6H14)': 86.18,
    'Heptane (C7H16)': 100.21,
    'Octane (C8H18)': 114.23,
    'Benzene (C6H6)': 78.11,
    'Toluene (C7H8)': 92.14,
    'Methanol (CH3OH)': 32.04,
    'Ethanol (C2H5OH)': 46.07,
    'Diethyl Ether ((C2H5)2O)': 74.12
}

"""## Functions for Gas Identification

Here we define two functions:
1.  `calculate_molecular_weight`: Computes the molecular weight using the ideal gas law (PV = (mass/M)RT).
2.  `identify_gas`: Takes the calculated molecular weight and searches for a match within the `known_gases` list, considering the `ERROR_PERCENTAGE`.
"""

def calculate_molecular_weight(P, V, T, mass, R=R):
    """
    Calculates the molecular weight of a gas using the ideal gas law.

    Args:
        P (float): Pressure in atmospheres (atm).
        V (float): Volume in liters (L).
        T (float): Temperature in Kelvin (K).
        mass (float): Mass of the gas in grams (g).
        R (float): Ideal gas constant (L·atm/(mol·K)). Default is 0.082.

    Returns:
        float: Calculated molecular weight in g/mol.
    """
    # Ensure T is not zero to avoid division by zero
    if T == 0:
        raise ValueError("Temperature cannot be zero Kelvin.")
    # Ensure P and V are not zero or negative for meaningful calculation
    if P <= 0 or V <= 0:
        raise ValueError("Pressure and Volume must be positive.")
    # Ensure mass is positive
    if mass <= 0:
        raise ValueError("Mass must be positive.")

    # Ideal gas law: PV = nRT, where n = mass / M (Molecular Weight)
    # So, PV = (mass / M)RT
    # Rearranging for M: M = (mass * R * T) / (P * V)
    molecular_weight = (mass * R * T) / (P * V)
    return molecular_weight

def identify_gas(calculated_M, known_gases, error_percentage):
    """
    Identifies a gas by comparing its calculated molecular weight to a list of known gases
    within a specified error percentage.

    Args:
        calculated_M (float): The molecular weight calculated from experimental data.
        known_gases (dict): A dictionary where keys are gas names (str) and values are
                            their known molecular weights (float).
        error_percentage (float): The allowed percentage error for identification (e.g., 0.20 for 20%).

    Returns:
        str: The identified gas name, or a message indicating no match found.
    """
    possible_matches = []
    for gas_name, known_M in known_gases.items():
        lower_bound = known_M * (1 - error_percentage)
        upper_bound = known_M * (1 + error_percentage)

        if lower_bound <= calculated_M <= upper_bound:
            possible_matches.append(gas_name)

    if not possible_matches:
        return "No matching gas found within the specified error range."
    elif len(possible_matches) == 1:
        return f"Identified Gas: {possible_matches[0]} (Calculated M: {calculated_M:.2f} g/mol)"
    else:
        return f"Multiple possible matches found: {', '.join(possible_matches)} (Calculated M: {calculated_M:.2f} g/mol)"

"""## Demonstration

Let's test the device with some example values.
"""

# Example 1: Known gas (e.g., Nitrogen N2)
P_ex1 = 1.0     # atm
V_ex1 = 22.4    # L (approx. molar volume at STP)
T_ex1 = 273.15  # K (0 degrees Celsius)
mass_ex1 = 28.01 # g (approx. mass of 1 mole of N2)

calculated_M_ex1 = calculate_molecular_weight(P_ex1, V_ex1, T_ex1, mass_ex1)
print(f"Example 1 - Calculated Molecular Weight: {calculated_M_ex1:.2f} g/mol")
identification_ex1 = identify_gas(calculated_M_ex1, known_gases, ERROR_PERCENTAGE)
print(f"Example 1 - {identification_ex1}\n")

# Example 2: Another known gas (e.g., Carbon Dioxide CO2)
P_ex2 = 1.2     # atm
V_ex2 = 20.0    # L
T_ex2 = 300.0   # K
mass_ex2 = 48.0 # g (slightly more than 1 mole of CO2)

calculated_M_ex2 = calculate_molecular_weight(P_ex2, V_ex2, T_ex2, mass_ex2)
print(f"Example 2 - Calculated Molecular Weight: {calculated_M_ex2:.2f} g/mol")
identification_ex2 = identify_gas(calculated_M_ex2, known_gases, ERROR_PERCENTAGE)
print(f"Example 2 - {identification_ex2}\n")

# Example 3: Values that might not match perfectly or result in multiple matches
P_ex3 = 0.95    # atm
V_ex3 = 25.0    # L
T_ex3 = 280.0   # K
mass_ex3 = 20.0 # g (hypothetical)

calculated_M_ex3 = calculate_molecular_weight(P_ex3, V_ex3, T_ex3, mass_ex3)
print(f"Example 3 - Calculated Molecular Weight: {calculated_M_ex3:.2f} g/mol")
identification_ex3 = identify_gas(calculated_M_ex3, known_gases, ERROR_PERCENTAGE)
print(f"Example 3 - {identification_ex3}")

"""## Interactive Gas Identification

Use the input fields below to adjust the parameters and identify an unknown gas.

## Custom Interactive Interface

Below is a custom UI with a dedicated **Calculate** button.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# Create input widgets
p_input = widgets.FloatText(value=1.0, description='P (atm):')
v_input = widgets.FloatText(value=22.4, description='V (L):')
t_input = widgets.FloatText(value=273.15, description='T (K):')
mass_input = widgets.FloatText(value=28.01, description='Mass (g):')
error_slider = widgets.FloatSlider(value=0.1, min=0, max=0.5, step=0.01, description='Error (%):')
calc_button = widgets.Button(description="계산하기", button_style='primary')
output_area = widgets.Output()

def on_button_clicked(b):
    with output_area:
        clear_output()
        try:
            calc_M = calculate_molecular_weight(p_input.value, v_input.value, t_input.value, mass_input.value)
            res = identify_gas(calc_M, known_gases, error_slider.value)
            print(f"[결과] 계산된 분자량: {calc_M:.2f} g/mol")
            print(res)
        except Exception as e:
            print(f"오류 발생: {e}")

calc_button.on_click(on_button_clicked)

# Layout
ui = widgets.VBox([p_input, v_input, t_input, mass_input, error_slider, calc_button])
display(ui, output_area)