{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN4q9Gktvo4UAkJ6mwwZUND",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "version_major": 2,
        "version_minor": 0,
        "state": {
          "82d457c97f7b4f0fa1f2479f389b8a72": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "VBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "VBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "VBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_872df75fc399491da2497186dc7b459d",
                "IPY_MODEL_708b82ebc19b4618a7d0a91503101f4b",
                "IPY_MODEL_538ed35865b640b891384c57e7b2fba7",
                "IPY_MODEL_23b23e68f9844f9eaada1b5c647ae982",
                "IPY_MODEL_8ed2470ab2194354bf0b522e814985d9",
                "IPY_MODEL_2eeb6f2aa62145ddb956ca66ce0f52a2"
              ],
              "layout": "IPY_MODEL_20796840a7f44a33b24ee25efe7a319a"
            }
          },
          "872df75fc399491da2497186dc7b459d": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "P (atm):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_c2ef4ef5cfdc45599a9edfc506ea4420",
              "step": null,
              "style": "IPY_MODEL_97967c34ff7a45dcb22ba7b439864a52",
              "value": 1
            }
          },
          "708b82ebc19b4618a7d0a91503101f4b": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "V (L):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_908c82347a2a46009c299282e617a6a0",
              "step": null,
              "style": "IPY_MODEL_d5540e99209841b19ea82b8684c3af7a",
              "value": 22.4
            }
          },
          "538ed35865b640b891384c57e7b2fba7": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "T (K):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_a2307b8c37674cb994f62bfefa91b80c",
              "step": null,
              "style": "IPY_MODEL_ca4179799df74ab5afdd9c5082011e4a",
              "value": 273.15
            }
          },
          "23b23e68f9844f9eaada1b5c647ae982": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatTextModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatTextModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatTextView",
              "continuous_update": false,
              "description": "Mass (g):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_21f0281cefc84195a005e17c4274ef3f",
              "step": null,
              "style": "IPY_MODEL_a69f8574523a4d4696ca64eb7e1988d6",
              "value": 2
            }
          },
          "8ed2470ab2194354bf0b522e814985d9": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatSliderModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatSliderModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "FloatSliderView",
              "continuous_update": true,
              "description": "Error (%):",
              "description_tooltip": null,
              "disabled": false,
              "layout": "IPY_MODEL_fdad8f1336ff49e291c17cad6f90fa20",
              "max": 0.5,
              "min": 0,
              "orientation": "horizontal",
              "readout": true,
              "readout_format": ".2f",
              "step": 0.01,
              "style": "IPY_MODEL_d71cb638f6c8498ab0107d65ccdd9195",
              "value": 0.1
            }
          },
          "2eeb6f2aa62145ddb956ca66ce0f52a2": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ButtonModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ButtonModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ButtonView",
              "button_style": "primary",
              "description": "계산하기",
              "disabled": false,
              "icon": "",
              "layout": "IPY_MODEL_8163969451574817afcf8d79814a775e",
              "style": "IPY_MODEL_2e8290d181ff46978cbe84768fbbd104",
              "tooltip": ""
            }
          },
          "20796840a7f44a33b24ee25efe7a319a": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "c2ef4ef5cfdc45599a9edfc506ea4420": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "97967c34ff7a45dcb22ba7b439864a52": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "908c82347a2a46009c299282e617a6a0": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "d5540e99209841b19ea82b8684c3af7a": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "a2307b8c37674cb994f62bfefa91b80c": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "ca4179799df74ab5afdd9c5082011e4a": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "21f0281cefc84195a005e17c4274ef3f": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "a69f8574523a4d4696ca64eb7e1988d6": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "fdad8f1336ff49e291c17cad6f90fa20": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "d71cb638f6c8498ab0107d65ccdd9195": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "SliderStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "SliderStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": "",
              "handle_color": null
            }
          },
          "8163969451574817afcf8d79814a775e": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "2e8290d181ff46978cbe84768fbbd104": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ButtonStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ButtonStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "button_color": null,
              "font_weight": ""
            }
          },
          "e472320ec7174ab7b8fc403d0d57db54": {
            "model_module": "@jupyter-widgets/output",
            "model_name": "OutputModel",
            "model_module_version": "1.0.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/output",
              "_model_module_version": "1.0.0",
              "_model_name": "OutputModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/output",
              "_view_module_version": "1.0.0",
              "_view_name": "OutputView",
              "layout": "IPY_MODEL_4f8a1c9fa15741ad87205dcfdb434407",
              "msg_id": "",
              "outputs": [
                {
                  "output_type": "stream",
                  "name": "stdout",
                  "text": [
                    "[결과] 계산된 분자량: 2.00 g/mol\n",
                    "Identified Gas: Hydrogen (H2) (Calculated M: 2.00 g/mol)\n"
                  ]
                }
              ]
            }
          },
          "4f8a1c9fa15741ad87205dcfdb434407": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/tototo24-create/gdp-dashboard/blob/main/%EA%B5%90%EC%82%AC_%EC%97%B0%EC%88%98_%EC%88%98%EC%97%85%EC%9A%A9.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8de9f86b"
      },
      "source": [
        "# Gas Identification Device using Ideal Gas Law\n",
        "\n",
        "This notebook implements a simple device to identify an unknown ideal gas by measuring its pressure (P), volume (V), temperature (T), and mass. The identification is based on the calculated molecular weight (M) using the ideal gas law and comparing it against a list of known gases within a specified error range."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "269dd9c2"
      },
      "source": [
        "# Define the Ideal Gas Constant (R) and the allowed error percentage\n",
        "R = 0.082  # L·atm/(mol·K)\n",
        "ERROR_PERCENTAGE = 0.20 # 20% error margin"
      ],
      "execution_count": 34,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "f2f2e876"
      },
      "source": [
        "## 40 Representative Gases and their Molecular Weights\n",
        "\n",
        "Below is a list of 40 common gases with their approximate molecular weights (g/mol). This list will be used to identify the unknown gas. Please note that these are rounded values and may vary slightly depending on the source."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "2a908e8a"
      },
      "source": [
        "# Dictionary of known gases and their molecular weights (g/mol)\n",
        "known_gases = {\n",
        "    'Hydrogen (H2)': 2.016,\n",
        "    'Helium (He)': 4.003,\n",
        "    'Methane (CH4)': 16.04,\n",
        "    'Ammonia (NH3)': 17.03,\n",
        "    'Water Vapor (H2O)': 18.015,\n",
        "    'Neon (Ne)': 20.18,\n",
        "    'Nitrogen (N2)': 28.01,\n",
        "    'Carbon Monoxide (CO)': 28.01,\n",
        "    'Ethane (C2H6)': 30.07,\n",
        "    'Oxygen (O2)': 32.00,\n",
        "    'Hydrogen Sulfide (H2S)': 34.08,\n",
        "    'Argon (Ar)': 39.95,\n",
        "    'Carbon Dioxide (CO2)': 44.01,\n",
        "    'Nitrous Oxide (N2O)': 44.01,\n",
        "    'Propane (C3H8)': 44.10,\n",
        "    'Butane (C4H10)': 58.12,\n",
        "    'Sulfur Dioxide (SO2)': 64.07,\n",
        "    'Chlorine (Cl2)': 70.91,\n",
        "    'Krypton (Kr)': 83.80,\n",
        "    'Xenon (Xe)': 131.29,\n",
        "    'Sulfur Hexafluoride (SF6)': 146.06,\n",
        "    'Fluorine (F2)': 37.99,\n",
        "    'Ozone (O3)': 47.997,\n",
        "    'Nitric Oxide (NO)': 30.01,\n",
        "    'Nitrogen Dioxide (NO2)': 46.01,\n",
        "    'Hydrogen Chloride (HCl)': 36.46,\n",
        "    'Hydrogen Fluoride (HF)': 20.01,\n",
        "    'Ethylene (C2H4)': 28.05,\n",
        "    'Acetylene (C2H2)': 26.04,\n",
        "    'Propylene (C3H6)': 42.08,\n",
        "    'Butylene (C4H8)': 56.11,\n",
        "    'Pentane (C5H12)': 72.15,\n",
        "    'Hexane (C6H14)': 86.18,\n",
        "    'Heptane (C7H16)': 100.21,\n",
        "    'Octane (C8H18)': 114.23,\n",
        "    'Benzene (C6H6)': 78.11,\n",
        "    'Toluene (C7H8)': 92.14,\n",
        "    'Methanol (CH3OH)': 32.04,\n",
        "    'Ethanol (C2H5OH)': 46.07,\n",
        "    'Diethyl Ether ((C2H5)2O)': 74.12\n",
        "}"
      ],
      "execution_count": 35,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "61b6adf9"
      },
      "source": [
        "## Functions for Gas Identification\n",
        "\n",
        "Here we define two functions:\n",
        "1.  `calculate_molecular_weight`: Computes the molecular weight using the ideal gas law (PV = (mass/M)RT).\n",
        "2.  `identify_gas`: Takes the calculated molecular weight and searches for a match within the `known_gases` list, considering the `ERROR_PERCENTAGE`."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "5d52df01"
      },
      "source": [
        "def calculate_molecular_weight(P, V, T, mass, R=R):\n",
        "    \"\"\"\n",
        "    Calculates the molecular weight of a gas using the ideal gas law.\n",
        "\n",
        "    Args:\n",
        "        P (float): Pressure in atmospheres (atm).\n",
        "        V (float): Volume in liters (L).\n",
        "        T (float): Temperature in Kelvin (K).\n",
        "        mass (float): Mass of the gas in grams (g).\n",
        "        R (float): Ideal gas constant (L·atm/(mol·K)). Default is 0.082.\n",
        "\n",
        "    Returns:\n",
        "        float: Calculated molecular weight in g/mol.\n",
        "    \"\"\"\n",
        "    # Ensure T is not zero to avoid division by zero\n",
        "    if T == 0:\n",
        "        raise ValueError(\"Temperature cannot be zero Kelvin.\")\n",
        "    # Ensure P and V are not zero or negative for meaningful calculation\n",
        "    if P <= 0 or V <= 0:\n",
        "        raise ValueError(\"Pressure and Volume must be positive.\")\n",
        "    # Ensure mass is positive\n",
        "    if mass <= 0:\n",
        "        raise ValueError(\"Mass must be positive.\")\n",
        "\n",
        "    # Ideal gas law: PV = nRT, where n = mass / M (Molecular Weight)\n",
        "    # So, PV = (mass / M)RT\n",
        "    # Rearranging for M: M = (mass * R * T) / (P * V)\n",
        "    molecular_weight = (mass * R * T) / (P * V)\n",
        "    return molecular_weight\n",
        "\n",
        "def identify_gas(calculated_M, known_gases, error_percentage):\n",
        "    \"\"\"\n",
        "    Identifies a gas by comparing its calculated molecular weight to a list of known gases\n",
        "    within a specified error percentage.\n",
        "\n",
        "    Args:\n",
        "        calculated_M (float): The molecular weight calculated from experimental data.\n",
        "        known_gases (dict): A dictionary where keys are gas names (str) and values are\n",
        "                            their known molecular weights (float).\n",
        "        error_percentage (float): The allowed percentage error for identification (e.g., 0.20 for 20%).\n",
        "\n",
        "    Returns:\n",
        "        str: The identified gas name, or a message indicating no match found.\n",
        "    \"\"\"\n",
        "    possible_matches = []\n",
        "    for gas_name, known_M in known_gases.items():\n",
        "        lower_bound = known_M * (1 - error_percentage)\n",
        "        upper_bound = known_M * (1 + error_percentage)\n",
        "\n",
        "        if lower_bound <= calculated_M <= upper_bound:\n",
        "            possible_matches.append(gas_name)\n",
        "\n",
        "    if not possible_matches:\n",
        "        return \"No matching gas found within the specified error range.\"\n",
        "    elif len(possible_matches) == 1:\n",
        "        return f\"Identified Gas: {possible_matches[0]} (Calculated M: {calculated_M:.2f} g/mol)\"\n",
        "    else:\n",
        "        return f\"Multiple possible matches found: {', '.join(possible_matches)} (Calculated M: {calculated_M:.2f} g/mol)\""
      ],
      "execution_count": 36,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "61df4fc6"
      },
      "source": [
        "## Demonstration\n",
        "\n",
        "Let's test the device with some example values."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "62634d04",
        "outputId": "68e151c1-1f77-4ac1-9a00-268fd3e998b1"
      },
      "source": [
        "# Example 1: Known gas (e.g., Nitrogen N2)\n",
        "P_ex1 = 1.0     # atm\n",
        "V_ex1 = 22.4    # L (approx. molar volume at STP)\n",
        "T_ex1 = 273.15  # K (0 degrees Celsius)\n",
        "mass_ex1 = 28.01 # g (approx. mass of 1 mole of N2)\n",
        "\n",
        "calculated_M_ex1 = calculate_molecular_weight(P_ex1, V_ex1, T_ex1, mass_ex1)\n",
        "print(f\"Example 1 - Calculated Molecular Weight: {calculated_M_ex1:.2f} g/mol\")\n",
        "identification_ex1 = identify_gas(calculated_M_ex1, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 1 - {identification_ex1}\\n\")\n",
        "\n",
        "# Example 2: Another known gas (e.g., Carbon Dioxide CO2)\n",
        "P_ex2 = 1.2     # atm\n",
        "V_ex2 = 20.0    # L\n",
        "T_ex2 = 300.0   # K\n",
        "mass_ex2 = 48.0 # g (slightly more than 1 mole of CO2)\n",
        "\n",
        "calculated_M_ex2 = calculate_molecular_weight(P_ex2, V_ex2, T_ex2, mass_ex2)\n",
        "print(f\"Example 2 - Calculated Molecular Weight: {calculated_M_ex2:.2f} g/mol\")\n",
        "identification_ex2 = identify_gas(calculated_M_ex2, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 2 - {identification_ex2}\\n\")\n",
        "\n",
        "# Example 3: Values that might not match perfectly or result in multiple matches\n",
        "P_ex3 = 0.95    # atm\n",
        "V_ex3 = 25.0    # L\n",
        "T_ex3 = 280.0   # K\n",
        "mass_ex3 = 20.0 # g (hypothetical)\n",
        "\n",
        "calculated_M_ex3 = calculate_molecular_weight(P_ex3, V_ex3, T_ex3, mass_ex3)\n",
        "print(f\"Example 3 - Calculated Molecular Weight: {calculated_M_ex3:.2f} g/mol\")\n",
        "identification_ex3 = identify_gas(calculated_M_ex3, known_gases, ERROR_PERCENTAGE)\n",
        "print(f\"Example 3 - {identification_ex3}\")"
      ],
      "execution_count": 37,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Example 1 - Calculated Molecular Weight: 28.01 g/mol\n",
            "Example 1 - Multiple possible matches found: Nitrogen (N2), Carbon Monoxide (CO), Ethane (C2H6), Oxygen (O2), Hydrogen Sulfide (H2S), Nitric Oxide (NO), Ethylene (C2H4), Acetylene (C2H2), Methanol (CH3OH) (Calculated M: 28.01 g/mol)\n",
            "\n",
            "Example 2 - Calculated Molecular Weight: 49.20 g/mol\n",
            "Example 2 - Multiple possible matches found: Carbon Dioxide (CO2), Nitrous Oxide (N2O), Propane (C3H8), Butane (C4H10), Ozone (O3), Nitrogen Dioxide (NO2), Propylene (C3H6), Butylene (C4H8), Ethanol (C2H5OH) (Calculated M: 49.20 g/mol)\n",
            "\n",
            "Example 3 - Calculated Molecular Weight: 19.33 g/mol\n",
            "Example 3 - Multiple possible matches found: Ammonia (NH3), Water Vapor (H2O), Neon (Ne), Hydrogen Fluoride (HF) (Calculated M: 19.33 g/mol)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "3cd48b88"
      },
      "source": [
        "## Interactive Gas Identification\n",
        "\n",
        "Use the input fields below to adjust the parameters and identify an unknown gas."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "cee2cd57"
      },
      "source": [
        "## Custom Interactive Interface\n",
        "\n",
        "Below is a custom UI with a dedicated **Calculate** button."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 249,
          "referenced_widgets": [
            "82d457c97f7b4f0fa1f2479f389b8a72",
            "872df75fc399491da2497186dc7b459d",
            "708b82ebc19b4618a7d0a91503101f4b",
            "538ed35865b640b891384c57e7b2fba7",
            "23b23e68f9844f9eaada1b5c647ae982",
            "8ed2470ab2194354bf0b522e814985d9",
            "2eeb6f2aa62145ddb956ca66ce0f52a2",
            "20796840a7f44a33b24ee25efe7a319a",
            "c2ef4ef5cfdc45599a9edfc506ea4420",
            "97967c34ff7a45dcb22ba7b439864a52",
            "908c82347a2a46009c299282e617a6a0",
            "d5540e99209841b19ea82b8684c3af7a",
            "a2307b8c37674cb994f62bfefa91b80c",
            "ca4179799df74ab5afdd9c5082011e4a",
            "21f0281cefc84195a005e17c4274ef3f",
            "a69f8574523a4d4696ca64eb7e1988d6",
            "fdad8f1336ff49e291c17cad6f90fa20",
            "d71cb638f6c8498ab0107d65ccdd9195",
            "8163969451574817afcf8d79814a775e",
            "2e8290d181ff46978cbe84768fbbd104",
            "e472320ec7174ab7b8fc403d0d57db54",
            "4f8a1c9fa15741ad87205dcfdb434407"
          ]
        },
        "id": "63579ac3",
        "outputId": "0f45758b-21e3-4eaf-faf0-22eb63d457e2"
      },
      "source": [
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "\n",
        "# Create input widgets\n",
        "p_input = widgets.FloatText(value=1.0, description='P (atm):')\n",
        "v_input = widgets.FloatText(value=22.4, description='V (L):')\n",
        "t_input = widgets.FloatText(value=273.15, description='T (K):')\n",
        "mass_input = widgets.FloatText(value=28.01, description='Mass (g):')\n",
        "error_slider = widgets.FloatSlider(value=0.1, min=0, max=0.5, step=0.01, description='Error (%):')\n",
        "calc_button = widgets.Button(description=\"계산하기\", button_style='primary')\n",
        "output_area = widgets.Output()\n",
        "\n",
        "def on_button_clicked(b):\n",
        "    with output_area:\n",
        "        clear_output()\n",
        "        try:\n",
        "            calc_M = calculate_molecular_weight(p_input.value, v_input.value, t_input.value, mass_input.value)\n",
        "            res = identify_gas(calc_M, known_gases, error_slider.value)\n",
        "            print(f\"[결과] 계산된 분자량: {calc_M:.2f} g/mol\")\n",
        "            print(res)\n",
        "        except Exception as e:\n",
        "            print(f\"오류 발생: {e}\")\n",
        "\n",
        "calc_button.on_click(on_button_clicked)\n",
        "\n",
        "# Layout\n",
        "ui = widgets.VBox([p_input, v_input, t_input, mass_input, error_slider, calc_button])\n",
        "display(ui, output_area)"
      ],
      "execution_count": 38,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "VBox(children=(FloatText(value=1.0, description='P (atm):'), FloatText(value=22.4, description='V (L):'), Floa…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "82d457c97f7b4f0fa1f2479f389b8a72"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Output()"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "e472320ec7174ab7b8fc403d0d57db54"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}
